name: Lint and Build

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker build .
